import Head from "next/head";
import Image from "next/image";
import { Griffy, Inter, Prompt } from "next/font/google";
import styles from "@/styles/Home.module.css";
import {
  Box,
  Button,
  FormControlLabel,
  FormHelperText,
  Grid,
  IconButton,
  Paper,
  Radio,
  RadioGroup,
  TextField,
  Typography,
} from "@mui/material";
import DeleteOutlineIcon from "@mui/icons-material/DeleteOutline";
import AddIcon from "@mui/icons-material/Add";
import ContentCopyIcon from "@mui/icons-material/ContentCopy";
import React, { ChangeEvent, useState } from "react";
import { SettingsApplicationsSharp } from "@mui/icons-material";
import DynamicTwoInput from "./test";
import DynamicInput from "./test";

export default function Home() {
  const [questionnaire, setQuestionnaire] = useState("");
  // console.log('Questionnaire: '+ questionnaire)
  // const [helperText, setHelperText] = React.useState(' ');

  const [allData, setAllData] = useState([
    {
      question: "",
      description: [
        { option: false, detail: "", helptext: "" },
        { option: false, detail: "", helptext: "" },
      ],
    },
  ]);

  const handleDuplicate = () => {
    console.table(allData);
  };

  const handleAddQuestion = () => {
    let _allData = [...allData];
    _allData.push({
      question: "",
      description: [
        {
          option: false,
          detail: "",
          helptext: "",
        },
        {
          option: false,
          detail: "",
          helptext: "",
        },
      ],
    });
    setAllData(_allData);
  };

  const handleQuestionChange = (e: React.ChangeEvent<HTMLInputElement>, i) => {
    const { name, value } = e.target;
    const _allData = [...allData] as any;
    _allData[i][name] = value;
    setAllData(_allData);
  };

  // const handleRadioChange = (e: React.ChangeEvent<HTMLInputElement>, i, j) => {
  //   const { checked } = e.target;
  //   const _allData = [...allData];
  //   _allData[i].description[j].option = checked;
  //   console.log(i,j,_allData[i].description[j].option);
  //   console.log(_allData);
  //   // setAllData(_allData)

  //   // if(_allData[i].description[j].option === true){
  //   //   setHelperText('This answer is correct.');
  //   // }
  //   // else{
  //   //   setHelperText(' ');
  //   // }

  //   console.log(i, j, checked)

  // };

  const handleRadio = (i, j) => {
    console.log(i, j, "index_val");

    const _allData = [...allData];

    allData[i].description.map((data, x) => {
      if (j == x) {
        data.option = true;
        data.helptext = "This answer is correct";
      } else {
        data.option = false;
        data.helptext = "";
      }
      console.log(data);
    });
    setAllData(_allData);
    console.log(allData);
  };

  const handleDescriptionChange = (
    e: React.ChangeEvent<HTMLInputElement>,
    i,
    j
  ) => {
    const { name, value } = e.target;
    const _allData = [...allData] as any;
    _allData[i].description[j][name] = value;
    setAllData(_allData);
    console.log(allData);
  };

  const handleAddDescription = (i: number) => {
    const _allData = [...allData];
    _allData[i].description.push({
      option: false,
      detail: "",
      helptext: "",
    });
    setAllData(_allData);
  };

  const handleDescriptionDelete = (i, j) => {
    const deleteVal = [...allData];
    deleteVal[i].description.splice(j, 1);
    setAllData(deleteVal);
  };

  const handleQuestionDelete = (i: any) => {
    const deleteVal = [...allData];
    deleteVal.splice(i, 1);
    setAllData(deleteVal);
  };

  return (
    <>
      <Head>
        <title>Foxbith Questionnaire</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        sx={{ "& button": { m: 1 } }}
        paddingY={1}
        className={styles.navBar}
      >
        <Grid className={styles.logo} marginY={2} marginLeft={3}>
          🦊 Foxbith Questionnaire
        </Grid>
        <hr />
        <Grid
          margin={1.5}
          display={"flex"}
          justifyContent={"flex-end"}
          alignItems={"center"}
        >
          <Button
            variant="outlined"
            size="large"
            sx={{
              color: "#FF5C00",
              border: "1px solid #FF5C00",
              "&:hover": { borderColor: "#d95000" },
              px: 2,
            }}
          >
            cancel
          </Button>

          <Button
            variant="contained"
            size="large"
            sx={{
              color: "#FFF",
              backgroundColor: "#FF5C00",
              "&:hover": { backgroundColor: "#d95000" },
              width: 180,
              px: 2,
            }}
          >
            save
          </Button>
        </Grid>
      </Grid>

      {/* Question */}
      <Box component="form" sx={{ background: "#F3F4F6" }}>
        <Paper sx={{ margin: 3 }}>
          <Grid sx={{ p: 3 }}>
            <Typography className={styles.question} paddingBottom={3}>
              Questionnaire Detail
            </Typography>
            <TextField
              required
              id="outlined-required"
              fullWidth
              label="Questionnaire"
              name="questionnaire"
              value={questionnaire}
              onChange={(e) => {
                setQuestionnaire(e.target.value);
              }}
            />
          </Grid>
          <hr />

          {allData.map((allval, i) => (
            <Grid sx={{ p: 3 }}>
              <Grid>
                <Typography className={styles.question} paddingBottom={3}>
                  Question {i + 1}
                </Typography>
                <TextField
                  required
                  id="outlined-required"
                  sx={{ mb: 3 }}
                  fullWidth
                  label="Question"
                  name="question"
                  value={allval.question}
                  onChange={(e) => handleQuestionChange(e, i)}
                />

                {/* description */}
                {allval.description.map((val, j) => (
                  <Grid display={"flex"} alignItems={"center"} sx={{ mb: 3 }}>
                    <RadioGroup
                      sx={{
                        display: "flex",
                        flexWrap: "nowrap",
                        flexDirection: "row",
                      }}
                      onChange={() => handleRadio(i, j)}
                      // onChange={(e) => handleRadioChange(e, i, j)}
                    >
                      <FormControlLabel
                        control={<Radio checked={val.option} />}
                        label=""
                        name="Check"
                      />
                    </RadioGroup>
                    <TextField
                      required
                      id="outlined-required"
                      fullWidth
                      label="Description"
                      name="detail"
                      helperText={val.helptext}
                      value={val.detail}
                      onChange={(e) => handleDescriptionChange(e, i, j)}
                    />
                    <IconButton
                      aria-label="delete"
                      onClick={() => handleDescriptionDelete(i, j)}
                    >
                      <DeleteOutlineIcon />
                    </IconButton>
                  </Grid>
                ))}

                <Button
                  variant="text"
                  sx={{
                    color: "#FF5C00",
                    "&:hover": { color: "#d95000" },
                  }}
                  startIcon={<AddIcon />}
                  onClick={() => {
                    handleAddDescription(i);
                  }}
                >
                  ADD CHOICE
                </Button>
                <hr className={styles.hr} />
                <Grid>
                  <Button
                    variant="text"
                    sx={{
                      color: "#000",
                      "&:hover": { color: "#123456" },
                    }}
                    startIcon={<ContentCopyIcon />}
                    onClick={handleDuplicate}
                  >
                    DUPLICATE
                  </Button>
                  <Button
                    variant="text"
                    sx={{
                      color: "#000",
                      "&:hover": { color: "#ff0000" },
                    }}
                    startIcon={<DeleteOutlineIcon />}
                    onClick={() => handleQuestionDelete(i)}
                  >
                    DELETE
                  </Button>
                </Grid>
              </Grid>
            </Grid>
          ))}

          <hr />

          <Grid
            display={"flex"}
            flexDirection={"column"}
            // sx={{ "& button": { m: 1 } }}
            className={styles.navBar}
            p={3}
          >
            <Button
              variant="outlined"
              size="large"
              sx={{
                color: "#FF5C00",
                border: "1px solid #FF5C00",
                "&:hover": { borderColor: "#d95000", color: "#d95000" },
                px: 2,
              }}
              startIcon={<AddIcon />}
              onClick={handleAddQuestion}
            >
              Add Question
            </Button>
          </Grid>
        </Paper>
      </Box>
      {/* <DynamicInput /> */}
    </>
  );
}
